INSERT INTO ACCOUNT (ACCOUNT_ID, PASSWORD) VALUES ('admin', '$2a$10$nOXwPY9kf2JEvCB.Xp/GaO8EL2RzoxcDdycdIp8AJATCSAvS94hD6');
INSERT INTO ACCOUNT (ACCOUNT_ID, PASSWORD) VALUES ('user', '$2a$10$WyEXpoYsTm1bsuva7TldVesPn8RWTtZeLUkOZfGw9Ol.kq/qHnUiC');

INSERT INTO ROLE (ROLE_ID, ROLE_NAME) values (1, 'ROLE_ADMIN');
INSERT INTO ROLE (ROLE_ID, ROLE_NAME) values (2, 'ROLE_USER');

INSERT INTO ACCOUNT_ROLE (ACCOUNT_ID, ROLE_ID) values ('admin', 1);
INSERT INTO ACCOUNT_ROLE (ACCOUNT_ID, ROLE_ID) values ('user', 2);