spring:
  # DB
  datasource:
    url: jdbc:mariadb://localhost:3307/license_service_db?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

  # JPA
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    generate-ddl: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: never
      data-locations: classpath:sql/data.sql
      encoding: UTF-8

# JWT
jwt:
  header: Authorization
  bearer: Bearer
  secret: dGVhbWRldi1saWNlbnNlc2VydmljZS1qd3QtbXktc2VjcmV0LWtleS10ZWFtZGV2LWxpY2Vuc2VzZXJ2aWNlLWp3dC1teS1zZWNyZXQta2V5LXRlYW1kZXYtbGljZW5zZXNlcnZpY2Utand0LW15LXNlY3JldC1rZXk=
  token-validity-in-seconds: 86400

# Log
logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    com.teamdev.licenseservice: DEBUG
